<#
.SYNOPSIS
    计算并落盘"构建输入内容指纹"（docs/49 切片 1 的 2b）。
    由 3FCompare.csproj 的 GenerateSourceFingerprint 目标在每次编译前调用，
    也可由 tools/验证守卫.ps1 -Fingerprint 单独调用来做逐项比对。

.DESCRIPTION
    为什么不用纯 MSBuild 实现（两条都实测踩过）：
      · Item Include 属性值里的结尾 `;` 会被当列表分隔符吃掉，写成 &#59; 同样被吃；
      · @(_Items->'%(Hash)') 里 GetFileHash 的元数据在变换中展开成空串。
    ⇒ 逻辑放这里，MSBuild 只负责调用与把生成的 .cs 挂进 Compile。

    产物两个：
      1) -OutCs  : 编进程序集的常量（日志 [产物] 行打它的短摘要）
      2) -OutTxt : 输出目录里的 source-fingerprint.txt（守卫逐项比对的基准）
    指纹集合 = 本工程目录下所有 .cs / .axaml（排除 bin\ obj\），
    每项 "相对路径=SHA256(小写)"，按路径排序后用 '|' 连接。

    ⚠ 覆盖面只有 App 工程自身：Core / native / 内核 DLL 不在其中，
      那部分陈旧由验证守卫的 mtime 逐类别比较兜底。
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ProjectDir,
    [string]$OutCs = '',
    [string]$OutTxt = '',
    # 单独校验模式：把"当前源码算出的指纹"与给定的基准 txt 比对，列出差异文件名
    [string]$CompareTo = ''
)

$ErrorActionPreference = 'Stop'
$ProjectDir = (Resolve-Path -LiteralPath $ProjectDir).Path.TrimEnd('\')

function Get-Fingerprint([string]$root) {
    $rows = foreach ($f in [System.IO.Directory]::GetFiles($root, '*', [System.IO.SearchOption]::AllDirectories)) {
        if ($f -match '\\(bin|obj)\\') { continue }
        $ext = [System.IO.Path]::GetExtension($f)
        if ($ext -ne '.cs' -and $ext -ne '.axaml') { continue }
        $hash = (Get-FileHash -LiteralPath $f -Algorithm SHA256).Hash.ToLowerInvariant()
        [pscustomobject]@{ Rel = $f.Substring($root.Length + 1).Replace('\', '/'); Hash = $hash }
    }
    $sorted = $rows | Sort-Object Rel
    $joined = ($sorted | ForEach-Object { "$($_.Rel)=$($_.Hash)" }) -join '|'
    [pscustomobject]@{
        Count  = @($sorted).Count
        Concat = $joined
        Rows   = $sorted
    }
}

if ($CompareTo) {
    if (-not (Test-Path -LiteralPath $CompareTo)) {
        Write-Host "  ✗ 找不到基准指纹文件 $CompareTo" -ForegroundColor Red
        exit 5
    }
    $cur = Get-Fingerprint $ProjectDir
    $base = (Get-Content -LiteralPath $CompareTo -Raw).Trim()
    $baseRows = @{}
    foreach ($e in $base.Split('|')) {
        $i = $e.LastIndexOf('=')
        if ($i -gt 0) { $baseRows[$e.Substring(0, $i)] = $e.Substring($i + 1) }
    }
    $diff = @()
    foreach ($r in $cur.Rows) {
        if (-not $baseRows.ContainsKey($r.Rel)) { $diff += "新增: $($r.Rel)" }
        elseif ($baseRows[$r.Rel] -ne $r.Hash) { $diff += "已改动未编入: $($r.Rel)" }
    }
    foreach ($k in $baseRows.Keys) {
        if (-not ($cur.Rows.Rel -contains $k)) { $diff += "基准里有而现在没有(删除未编入): $k" }
    }
    Write-Host ("  指纹比对：当前 {0} 项 vs 基准 {1} 项 ⇒ {2}" -f `
        $cur.Count, $baseRows.Count, $(if ($diff.Count) { "不一致（$($diff.Count) 项）" } else { "一致" }))
    foreach ($d in ($diff | Select-Object -First 12)) { Write-Host "    - $d" -ForegroundColor Yellow }
    exit $(if ($diff.Count) { 3 } else { 0 })
}

$fp = Get-Fingerprint $ProjectDir

if ($OutCs) {
    $dir = Split-Path -Parent $OutCs
    if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    # 只在内容变化时改写，避免每次构建都戳新 mtime 引发无谓重编
    $body = @(
        '// <auto-generated /> 由 tools/源码指纹.ps1 在编译前生成，勿手改（docs/49）'
        'namespace _3FCompare.BuildInfo;'
        'internal static class SourceFingerprint {'
        "    internal const int FileCount = $($fp.Count);"
        "    internal const string Value = `"$($fp.Concat)`";"
        '}'
    )
    $want = ($body -join "`r`n") + "`r`n"
    $now = if (Test-Path -LiteralPath $OutCs) { [System.IO.File]::ReadAllText($OutCs) } else { '' }
    if ($now -ne $want) { [System.IO.File]::WriteAllText($OutCs, $want) }
}

if ($OutTxt) {
    $dir = Split-Path -Parent $OutTxt
    if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $now = if (Test-Path -LiteralPath $OutTxt) { [System.IO.File]::ReadAllText($OutTxt) } else { '' }
    if ($now -ne $fp.Concat) { [System.IO.File]::WriteAllText($OutTxt, $fp.Concat) }
}

Write-Host ("  源码指纹：{0} 个输入，摘要 {1}" -f $fp.Count,
    ([System.BitConverter]::ToString(
        [System.Security.Cryptography.SHA256]::Create().ComputeHash(
            [System.Text.Encoding]::UTF8.GetBytes($fp.Concat))).Replace('-', '').Substring(0, 16).ToLowerInvariant()))
exit 0
